export const projects = [
  {
    id: 1,
    title: "Asu Students App",
    date: "22, january, 2025",
    image: "/wallpaper.png",
    description:
      "A mobile app built with React Native to help university students manage academic life — GPA tracking, schedule organization, and more. Currently in beta.",
    live: "https://uni-site-nu.vercel.app/",
    source: "https://github.com/Natnsis/asu_students_appV2.0",
    isLive: true,
    tags: ["ReactNative", "TypeScript", "Node.js", "NeonDb"],
  },
  {
    id: 2,
    title: "Mini Chat App",
    date: "22, january, 2025",
    image: "/wallpaper.png",
    description:
      "A real time chat app with seamless mobile, and desktop responsiveness, with authentication and free chatting functionality.",
    live: "http://localhost/haha",
    source: "http://github.com/Natnsis/chat-app",
    isLive: false,
    tags: ["React.js", "Tailwindcss", "Node.js", "Socket.io"],
  },
  {
    id: 3,
    title: "HR Management System",
    date: "22, january, 2025",
    image: "/wallpaper.png",
    description:
      "A foundational HRMS built using Angular (TypeScript) to demonstrate proficiency with alternative frontend frameworks and design patterns outside the React ecosystem. This application features full CRUD functionality for managing employee records, offering a clean, modern interface and a lightweight architecture.",
    live: "",
    source: "https://github.com/Natnsis/Human-Resource",
    isLive: false,
    tags: ["Angular.js", "Tailwind", "In-Memory-Db"],
  },
  {
    id: 4,
    title: "E-commerce Platform",
    date: "22, january, 2025",
    image: "/wallpaper.png",
    description:
      "A comprehensive, scalable e-commerce solution engineered for robust performance and a seamless user experience. This platform features distinct operational roles (Admin, Vendor, Customer) and a secure, end-to-end purchasing lifecycle, from product browsing and cart management to secure payment processing.",
    live: "",
    source: "https://github.com/Natnsis/Ecommerce",
    isLive: false,
    tags: ["React.js", "Tailwind", "Node.js", "Stripe"],
  },
  {
    id: 5,
    title: "E-commerce Mobile App (Customer-Side)",
    date: "22, january, 2025",
    image: "/wallpaper.png",
    description:
      "A dedicated, cross-platform mobile application built with React Native to provide customers with an optimized and native-feeling mobile shopping experience. This project specifically focuses on the frontend client, consuming a back-end RESTful API to handle authentication, product retrieval, and secure checkout flows.",
    live: "",
    source: "https://github.com/Natnsis/ecommerce_mobile",
    isLive: false,
    tags: ["ReactNative", "Expo", "Node.js"],
  },
  {
    id: 6,
    title: "Clinic Management System",
    date: "22, january, 2025",
    image: "/wallpaper.png",
    description:
      "A full-stack web application designed to digitize and optimize the operations of a university clinic, replacing manual, paper-based workflows with an efficient, computer-based system. This platform significantly reduces administrative overhead, improves data accuracy, and streamlines patient care from check-in to treatment.",
    live: "",
    source: "https://github.com/Natnsis/clinic-management-system",
    isLive: false,
    tags: ["React.js", "Tailwind", "Node.js", "Zustand", "Zod", "Jwt"],
  },
  {
    id: 7,
    title: "Fimple",
    date: "22, january, 2025",
    image: "/wallpaper.png",
    description:
      "A custom, drop-in Neovim configuration designed for modern full-stack development using JavaScript, TypeScript, and Node.js. Built in Lua and centered on a 'zero-setup' philosophy, this configuration transforms Neovim into a lightweight, powerful IDE, focusing on efficiency, speed, and seamless integration with the tools developers use every day.",
    live: "",
    source: "https://github.com/Natnsis/simple_neovim_configuration",
    isLive: false,
    tags: ["Lua"],
  },
];
